# /// script
# requires-python = ">=3.14"
# dependencies = ["numpy>=2"]
# ///
"""Generate the numpy-derived golden vectors embedded in `test_rng.py`.

Run with `uv run --with numpy tests/generate_rng_vectors.py` (numpy is not a project
dependency, dev or otherwise) and paste the output into `test_rng.py`. The vectors were
generated once; regenerating them must reproduce the embedded values exactly — if it
doesn't, either numpy changed (it won't; PCG64 output is frozen) or the embedded values
were tampered with.

Two independent numpy anchors are produced:

- Output function: numpy's `PCG64` accepts raw `(state, inc)` through its `.state`
  property and exposes raw 64-bit outputs via `random_raw()`, giving canonical
  step/output vectors.
- Init procedure: numpy cannot be handed `(initstate, initseq)` directly (its seeding
  runs through `SeedSequence`), so we call `SeedSequence.generate_state(4, uint64)`
  ourselves, assemble `initstate = (w0 << 64) | w1` and `initseq = (w2 << 64) | w3`,
  and record numpy's post-seed `.state` — which exercises numpy's real
  `pcg64_srandom_r`. The test runs osrlib's init on the same pair and asserts the
  resulting `(state, inc)` matches.
"""

import numpy as np
from numpy.random import PCG64, SeedSequence

# Raw (state, inc) pairs for output-function vectors: the two 128-bit extremes plus a
# random-looking mid-range pair. inc must be odd (PCG increments always are).
RAW_PAIRS = [
    (1, 1),
    ((1 << 128) - 1, (1 << 128) - 1),
    (0x0123456789ABCDEF0123456789ABCDEF, 0xFEDCBA9876543210FEDCBA987654321B),
]

# SeedSequence entropy values for init-procedure vectors.
ENTROPIES = [0, 42, (1 << 127) + 12345]

DRAWS = 6


def output_vectors() -> list[tuple[int, int, list[int]]]:
    """Return `(state, inc, raw_outputs)` triples from numpy's step/output path."""
    vectors = []
    for state, inc in RAW_PAIRS:
        bg = PCG64()
        st = bg.state
        st["state"]["state"] = state
        st["state"]["inc"] = inc
        bg.state = st
        raw = [int(v) for v in bg.random_raw(DRAWS)]
        vectors.append((state, inc, raw))
    return vectors


def init_vectors() -> list[tuple[int, int, int, int, int, list[int]]]:
    """Return `(entropy, initstate, initseq, state, inc, raw_outputs)` init vectors."""
    vectors = []
    for entropy in ENTROPIES:
        words = SeedSequence(entropy).generate_state(4, np.uint64)
        initstate = (int(words[0]) << 64) | int(words[1])
        initseq = (int(words[2]) << 64) | int(words[3])
        bg = PCG64(SeedSequence(entropy))
        st = bg.state["state"]
        raw = [int(v) for v in bg.random_raw(DRAWS)]
        vectors.append((entropy, initstate, initseq, int(st["state"]), int(st["inc"]), raw))
    return vectors


def main() -> None:
    """Print the golden-vector constants for embedding in `test_rng.py`."""
    print(f"# Generated by generate_rng_vectors.py with numpy {np.__version__}.")
    print()
    print("# (state, inc) -> first six raw outputs, from numpy PCG64.random_raw().")
    print("NUMPY_OUTPUT_VECTORS = [")
    for state, inc, raw in output_vectors():
        print(f"    (0x{state:032X}, 0x{inc:032X}, [")
        for value in raw:
            print(f"        0x{value:016X},")
        print("    ]),")
    print("]")
    print()
    print("# (entropy, initstate, initseq, post-init state, inc, first six raw outputs),")
    print("# from numpy SeedSequence.generate_state(4, uint64) and PCG64(SeedSequence(...)).")
    print("NUMPY_INIT_VECTORS = [")
    for entropy, initstate, initseq, state, inc, raw in init_vectors():
        print(f"    ({entropy},")
        print(f"     0x{initstate:032X}, 0x{initseq:032X},")
        print(f"     0x{state:032X}, 0x{inc:032X}, [")
        for value in raw:
            print(f"        0x{value:016X},")
        print("    ]),")
    print("]")


if __name__ == "__main__":
    main()
