"""Tests for osrlib.core.rng — the determinism contract.

Golden-vector provenance
------------------------

Three independent anchors validate the PCG64 implementation, so no single oracle is
load-bearing:

- ``PCGC_REFERENCE_OUTPUTS``: known-answer values from O'Neill's pcg-c reference
  implementation, ``test-high/expected/check-pcg64.out`` Round 1 (the ``64bit:`` line),
  produced by ``pcg64_srandom_r(&rng, 42u, 54u)`` followed by six ``pcg64_random_r``
  calls (seed constants from ``test-high/check-pcg64.c``, ``XX_SRANDOM_SEEDCONSTS``).
  https://github.com/imneme/pcg-c, retrieved 2026-07-03.
- ``NUMPY_OUTPUT_VECTORS``: numpy's PCG64 handed raw ``(state, inc)`` pairs through its
  ``.state`` property, outputs via ``random_raw()`` — canonical step/output vectors.
- ``NUMPY_INIT_VECTORS``: numpy's real ``pcg64_srandom_r`` exercised through
  ``PCG64(SeedSequence(entropy))``, with the ``(initstate, initseq)`` pair recovered by
  calling ``SeedSequence.generate_state(4, uint64)`` ourselves and assembling
  ``initstate = (w0 << 64) | w1``, ``initseq = (w2 << 64) | w3``.

The numpy vectors were generated once by ``tests/generate_rng_vectors.py`` (run via
``uv run --with numpy``; numpy is not a project dependency) with numpy 2.5.0.

``SHA256_DERIVATION_VECTORS``, the ``randbelow`` goldens, and the rejection-branch
vector were generated from this implementation once its raw output, init, and
derivation paths were validated against the anchors above; they lock behavior against
accidental change rather than validating it against an external oracle.
"""

import hashlib

import pytest
from pydantic import ValidationError

from osrlib.core.dice import roll
from osrlib.core.rng import RngStream, RngStreams, RngStreamState, derive_init_pair

# fmt: off
# pcg-c check-pcg64.out Round 1: seed 42, seq 54 -> first six raw outputs.
PCGC_REFERENCE_SEED = (42, 54)
PCGC_REFERENCE_OUTPUTS = [
    0x86B1DA1D72062B68, 0x1304AA46C9853D39, 0xA3670E9E0DD50358,
    0xF9090E529A7DAE00, 0xC85B9FD837996F2C, 0x606121F8E3919196,
]
# fmt: on

# Generated by generate_rng_vectors.py with numpy 2.5.0.

# (state, inc) -> first six raw outputs, from numpy PCG64.random_raw().
NUMPY_OUTPUT_VECTORS = [
    (
        0x00000000000000000000000000000001,
        0x00000000000000000000000000000001,
        [
            0xE260E53261800AAB,
            0xD4FEB4E5A4BCFE09,
            0xE85A7FE071B026E6,
            0x3A5B9037FE928C11,
            0x7B044380D100F216,
            0x1C7850A6B6D83E6A,
        ],
    ),
    (
        0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,
        0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,
        [
            0xCA64C3001557C2C1,
            0xB4979FC13A9F569C,
            0x4DCDD0B4F1C0E360,
            0x946089D2DCC1BFF4,
            0x0B3D8221F0688079,
            0xE3C28531B6C1F350,
        ],
    ),
    (
        0x0123456789ABCDEF0123456789ABCDEF,
        0xFEDCBA9876543210FEDCBA987654321B,
        [
            0x4EAF8868BB16882E,
            0x1C5C48065B7DA603,
            0x9ABF52D7BB4AD01E,
            0x3F3B0B425C3CA704,
            0xA61975C6FE105D95,
            0x023236BB5B04ADE3,
        ],
    ),
]

# (entropy, initstate, initseq, post-init state, inc, first six raw outputs),
# from numpy SeedSequence.generate_state(4, uint64) and PCG64(SeedSequence(...)).
NUMPY_INIT_VECTORS = [
    (
        0,
        0xDB2CD7E7B0F478BEABF4641A2C71BA49,
        0x20C6ED6D9D7B8D412C4099DE223C39D4,
        0x1AA1B5345996452D09585EB7A69561E3,
        0x418DDADB3AF71A82588133BC447873A9,
        [
            0xA30FEBCFD9C2825F,
            0x4510BDF882D9D721,
            0x0A7D3DA94ECDE8B8,
            0x043B27B61342F01D,
            0xD0327A782CDE513B,
            0xE9AA5979A6401C4E,
        ],
    ),
    (
        42,
        0x9F1E2E6DCD540AB7D57873DC79FB94B6,
        0x7D282A1B64D420B7336579714692D5FF,
        0xCEA44F6798798F2AACBC7C9D68860AC8,
        0xFA505436C9A8416E66CAF2E28D25ABFF,
        [
            0xC621FBCD16D92688,
            0x705A5661A791FFC1,
            0xDBCD12C26EDA1624,
            0xB286B60E1600888D,
            0x181C01B5339381EB,
            0xF9C262ED86C7538C,
        ],
    ),
    (
        (1 << 127) + 12345,
        0x65921BFC82543D658181781755B18A54,
        0xFED290CC277ACFEB9E0B31CD703195B4,
        0x990B4DE47686AEFD115370D09037C55A,
        0xFDA521984EF59FD73C16639AE0632B69,
        [
            0xD10913040199D490,
            0x79BCFF517130F36E,
            0x7033E5F11304A046,
            0x764B1720B599309E,
            0x0578FD390A4F043D,
            0x80998B472D5242B7,
        ],
    ),
]

# (master_seed, key) -> (initstate, initseq): SHA-256(seed_16_bytes_be + b":" + key_utf8),
# digest bytes 0-15 big-endian = initstate, bytes 16-31 big-endian = initseq.
SHA256_DERIVATION_VECTORS = [
    (0, "combat", 0x2A8B5DE720DD8F2765D67A11DB991C9F, 0xC6A93387C9B852D203823B174D0B2E9A),
    (42, "treasure", 0xBC26E027280C646F46BFBA315D699637, 0x52176A1B0CDF870BDBEB63B5CE9F449F),
    ((1 << 128) - 1, "wandering", 0x043BF4978695D03724ABE99FBF8C7922, 0x34FCC07D976EFF978BEAF89DCB40F9E6),
]

# Locked randbelow sequences: master seed 42, one fresh stream per bound.
RANDBELOW_GOLDENS = [
    ("bounded", 20, [17, 17, 8, 8, 11, 3, 13, 15, 15, 8]),
    ("bounded", 6, [5, 4, 4, 2, 5, 2, 2, 5, 0, 3]),
    ("bounded", 100, [93, 71, 69, 33, 85, 35, 45, 94, 15, 55]),
]

# Locked raw outputs for the full derivation chain: master seed 42, key "combat".
DERIVED_STREAM_RAW_GOLDENS = [0xB1DDE5E900081B84, 0xDBB54E872EAF8F56, 0xAD406DA74899802A, 0x6A299D7EE49E00D7]


def draws_consumed(before: RngStreamState, after: RngStreamState) -> int:
    """Count raw draws separating two snapshots of the same stream."""
    clone = RngStream.restore(before)
    count = 0
    while clone.export_state() != after:
        clone.next_uint64()
        count += 1
        assert count <= 10_000, "snapshots are not on the same stream"
    return count


class TestGoldenVectors:
    def test_pcg_c_reference_known_answers(self):
        stream = RngStream(*PCGC_REFERENCE_SEED)
        assert [stream.next_uint64() for _ in PCGC_REFERENCE_OUTPUTS] == PCGC_REFERENCE_OUTPUTS

    @pytest.mark.parametrize(("state", "inc", "expected"), NUMPY_OUTPUT_VECTORS)
    def test_numpy_output_vectors(self, state, inc, expected):
        stream = RngStream.restore(RngStreamState(state=state, inc=inc))
        assert [stream.next_uint64() for _ in expected] == expected

    @pytest.mark.parametrize(("entropy", "initstate", "initseq", "state", "inc", "expected"), NUMPY_INIT_VECTORS)
    def test_numpy_init_vectors(self, entropy, initstate, initseq, state, inc, expected):
        stream = RngStream(initstate, initseq)
        snapshot = stream.export_state()
        assert (snapshot.state, snapshot.inc) == (state, inc)
        assert [stream.next_uint64() for _ in expected] == expected

    @pytest.mark.parametrize(("master_seed", "key", "initstate", "initseq"), SHA256_DERIVATION_VECTORS)
    def test_sha256_derivation_vectors(self, master_seed, key, initstate, initseq):
        assert derive_init_pair(master_seed, key) == (initstate, initseq)
        # Independent recomputation of the pinned construction.
        digest = hashlib.sha256(master_seed.to_bytes(16, "big") + b":" + key.encode("utf-8")).digest()
        assert int.from_bytes(digest[:16], "big") == initstate
        assert int.from_bytes(digest[16:], "big") == initseq

    def test_derived_stream_raw_goldens(self):
        stream = RngStream.from_seed_material(42, "combat")
        assert [stream.next_uint64() for _ in DERIVED_STREAM_RAW_GOLDENS] == DERIVED_STREAM_RAW_GOLDENS


class TestStreamDerivation:
    def test_same_seed_same_key_identical_sequences(self):
        a = RngStreams(master_seed=42).get("combat")
        b = RngStreams(master_seed=42).get("combat")
        assert [a.next_uint64() for _ in range(100)] == [b.next_uint64() for _ in range(100)]

    def test_reproducibility_contract_with_dice(self):
        # The definition-of-done demonstration: two independently derived streams from
        # the same master seed and key produce identical 2d6×10 roll sequences.
        streams_a = RngStreams(master_seed=42)
        streams_b = RngStreams(master_seed=42)
        rolls_a = [roll("2d6×10", streams_a.get("treasure")).total for _ in range(10)]
        rolls_b = [roll("2d6×10", streams_b.get("treasure")).total for _ in range(10)]
        assert rolls_a == rolls_b

    def test_different_keys_are_independent(self):
        # Drawing from one stream never shifts another.
        undisturbed = RngStreams(master_seed=42)
        expected = [undisturbed.get("treasure").next_uint64() for _ in range(20)]

        disturbed = RngStreams(master_seed=42)
        for _ in range(100):
            disturbed.get("combat").next_uint64()
        treasure = disturbed.get("treasure")
        drawn = []
        for _ in range(10):
            drawn.append(treasure.next_uint64())
            disturbed.get("combat").next_uint64()  # interleaved draws change nothing
        drawn += [treasure.next_uint64() for _ in range(10)]
        assert drawn == expected

    def test_different_keys_differ(self):
        streams = RngStreams(master_seed=42)
        assert streams.get("combat").next_uint64() != streams.get("treasure").next_uint64()

    def test_container_returns_same_stream_object(self):
        streams = RngStreams(master_seed=42)
        assert streams.get("combat") is streams.get("combat")

    def test_master_seed_property(self):
        assert RngStreams(master_seed=42).master_seed == 42

    @pytest.mark.parametrize("bad_seed", [-1, 1 << 128])
    def test_master_seed_out_of_range_raises(self, bad_seed):
        with pytest.raises(ValueError):
            RngStreams(master_seed=bad_seed)
        with pytest.raises(ValueError):
            derive_init_pair(bad_seed, "combat")

    @pytest.mark.parametrize("bad_value", [-1, 1 << 128])
    def test_init_pair_out_of_range_raises(self, bad_value):
        with pytest.raises(ValueError):
            RngStream(bad_value, 0)
        with pytest.raises(ValueError):
            RngStream(0, bad_value)


class TestRandbelow:
    @pytest.mark.parametrize(("key", "bound", "expected"), RANDBELOW_GOLDENS)
    def test_randbelow_goldens(self, key, bound, expected):
        stream = RngStream.from_seed_material(42, key)
        assert [stream.randbelow(bound) for _ in expected] == expected

    def test_rejection_branch(self):
        # Constructed vector: for master seed 42, key "reject-0", the first two raw
        # draws' top 5 bits are >= 20, so randbelow(20) rejects twice and consumes
        # three draws. The algorithm's most fragile path must not ship untested.
        probe = RngStream.from_seed_material(42, "reject-0")
        candidates = [probe.next_uint64() >> 59 for _ in range(3)]
        assert candidates[0] >= 20, "vector no longer exercises the rejection branch"
        assert candidates[1] >= 20, "vector no longer exercises the rejection branch"
        assert candidates[2] < 20

        stream = RngStream.from_seed_material(42, "reject-0")
        before = stream.export_state()
        assert stream.randbelow(20) == candidates[2] == 11
        assert draws_consumed(before, stream.export_state()) == 3

    def test_randbelow_one_always_zero_and_consumes_one_draw(self):
        stream = RngStream.from_seed_material(42, "ones")
        for _ in range(10):
            before = stream.export_state()
            assert stream.randbelow(1) == 0
            assert draws_consumed(before, stream.export_state()) == 1

    def test_power_of_two_bounds_never_reject(self):
        stream = RngStream.from_seed_material(42, "pow2")
        for bound in (2, 4, 8, 16):
            for _ in range(50):
                before = stream.export_state()
                assert 0 <= stream.randbelow(bound) < bound
                assert draws_consumed(before, stream.export_state()) == 1

    @pytest.mark.parametrize("bad_bound", [0, -1, -20])
    def test_nonpositive_bound_raises(self, bad_bound):
        stream = RngStream.from_seed_material(42, "bad")
        with pytest.raises(ValueError):
            stream.randbelow(bad_bound)

    def test_chi_square_uniformity(self):
        # Fixed seed so CI never flakes — this catches masking bugs, not cosmic rays.
        # Critical value for df=19 at p=0.001 is 43.82; the observed statistic for this
        # seed is ~13.1.
        stream = RngStream.from_seed_material(2025, "chi-square")
        bins = 20
        n = 10_000
        counts = [0] * bins
        for _ in range(n):
            counts[stream.randbelow(bins)] += 1
        expected = n / bins
        chi2 = sum((count - expected) ** 2 / expected for count in counts)
        assert chi2 < 43.82


class TestStateExportRestore:
    def test_roundtrip_continues_sequence(self):
        stream = RngStream.from_seed_material(42, "combat")
        for _ in range(17):
            stream.next_uint64()
        snapshot = stream.export_state()
        expected = [stream.next_uint64() for _ in range(20)]
        restored = RngStream.restore(snapshot)
        assert [restored.next_uint64() for _ in range(20)] == expected

    def test_snapshot_json_roundtrip(self):
        stream = RngStream.from_seed_material(42, "combat")
        stream.next_uint64()
        snapshot = stream.export_state()
        revived = RngStreamState.model_validate_json(snapshot.model_dump_json())
        assert revived == snapshot
        expected = stream.next_uint64()
        assert RngStream.restore(revived).next_uint64() == expected

    def test_export_does_not_disturb_stream(self):
        a = RngStream.from_seed_material(42, "combat")
        b = RngStream.from_seed_material(42, "combat")
        a.export_state()
        assert a.next_uint64() == b.next_uint64()

    def test_snapshot_rejects_even_inc(self):
        with pytest.raises(ValidationError):
            RngStreamState(state=0, inc=2)

    @pytest.mark.parametrize("field", ["state", "inc"])
    @pytest.mark.parametrize("bad_value", [-1, 1 << 128])
    def test_snapshot_rejects_out_of_range(self, field, bad_value):
        values = {"state": 0, "inc": 1}
        values[field] = bad_value
        with pytest.raises(ValidationError):
            RngStreamState(**values)
