"""Generated SRD data and its typed loaders.

The JSON files in this package are generated by `tools/srd_compile/` from the SRD
markdown in `srd/` and are never hand-edited — CI regenerates them and fails on any
diff. Regenerate with `uv run python -m tools.srd_compile`. Each file carries a `_meta`
block naming its source SRD pages; entries corrected by compiler overrides record the
touched field paths in `overrides_applied`.

Loaders read package resources, validate into frozen models, and cache: everything a
loader returns is immutable shared data — play spawns mutable instances from these
templates. Generated data that fails validation is malformed content and raises
[`ContentValidationError`][osrlib.errors.ContentValidationError].

The compiled data is Open Game Content under the Open Game License 1.0a; the license
text and Section 15 notice ship in this package as `LICENSE-OGL.md`.
"""

import json
from functools import cache
from importlib import resources

from pydantic import BaseModel, ConfigDict, ValidationError, model_validator

from osrlib.core.abilities import AbilityTables
from osrlib.core.classes import ClassCatalog
from osrlib.core.items import EquipmentCatalog
from osrlib.core.monsters import MonsterCatalog
from osrlib.core.spells import SpellCatalog
from osrlib.core.tables import CombatTables, EncounterTables
from osrlib.core.treasure import TreasureTables
from osrlib.errors import ContentValidationError

__all__ = [
    "Language",
    "LanguageCatalog",
    "load_ability_tables",
    "load_classes",
    "load_combat_tables",
    "load_encounter_tables",
    "load_equipment",
    "load_languages",
    "load_monsters",
    "load_spells",
    "load_treasure_tables",
]


class Language(BaseModel):
    """A language a character can speak.

    `choosable` marks the SRD's twenty Other Languages, available to characters with
    high INT; Common is not choosable (every class already speaks it natively).
    Alignment tongues are not data entries — they derive from the alignment enum.
    """

    model_config = ConfigDict(frozen=True)

    id: str
    name: str
    choosable: bool


class LanguageCatalog(BaseModel):
    """The loaded language list: Common plus the twenty Other Languages."""

    model_config = ConfigDict(frozen=True)

    languages: tuple[Language, ...]

    @model_validator(mode="after")
    def _ids_must_be_unique(self) -> LanguageCatalog:
        ids = [language.id for language in self.languages]
        if len(set(ids)) != len(ids):
            raise ValueError("language ids must be unique")
        return self

    def get(self, language_id: str) -> Language:
        """Return the language with `language_id`.

        Args:
            language_id: The language id, e.g. `"gnoll"`.

        Returns:
            The language.

        Raises:
            ValueError: If no language has that id.
        """
        for language in self.languages:
            if language.id == language_id:
                return language
        raise ValueError(f"unknown language id {language_id!r}")


def _read(filename: str) -> dict[str, object]:
    resource = resources.files("osrlib.data").joinpath(filename)
    try:
        text = resource.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise ContentValidationError(f"missing generated data file {filename!r}") from error
    data = json.loads(text)
    if not isinstance(data, dict):
        raise ContentValidationError(f"{filename} must contain a JSON object at the top level")
    data.pop("_meta", None)
    return data


@cache
def load_ability_tables() -> AbilityTables:
    """Load the six ability modifier tables and the prime requisite XP table.

    Returns:
        The frozen tables.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("abilities.json")
    try:
        return AbilityTables.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"abilities.json failed validation: {error}") from error


@cache
def load_classes() -> ClassCatalog:
    """Load the seven Classic class definitions.

    Returns:
        The frozen class catalog.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("classes.json")
    try:
        return ClassCatalog.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"classes.json failed validation: {error}") from error


@cache
def load_equipment() -> EquipmentCatalog:
    """Load the weapon, armour, gear, ammunition, and treasure-weight lists.

    Returns:
        The frozen equipment catalog.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("equipment.json")
    try:
        return EquipmentCatalog.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"equipment.json failed validation: {error}") from error


@cache
def load_monsters() -> MonsterCatalog:
    """Load the monster templates compiled from the SRD's monster pages.

    Returns:
        The frozen monster catalog.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("monsters.json")
    try:
        return MonsterCatalog.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"monsters.json failed validation: {error}") from error


@cache
def load_combat_tables() -> CombatTables:
    """Load the attack matrix, monster saving-throw bands, and XP-awards table.

    Returns:
        The frozen combat tables.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("combat_tables.json")
    try:
        return CombatTables.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"combat_tables.json failed validation: {error}") from error


@cache
def load_encounter_tables() -> EncounterTables:
    """Load the dungeon encounter tables by level.

    Returns:
        The frozen encounter tables.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("encounter_tables.json")
    try:
        return EncounterTables.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"encounter_tables.json failed validation: {error}") from error


@cache
def load_spells() -> SpellCatalog:
    """Load the spell templates compiled from the SRD's spell pages.

    Returns:
        The frozen spell catalog.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("spells.json")
    try:
        return SpellCatalog.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"spells.json failed validation: {error}") from error


@cache
def load_treasure_tables() -> TreasureTables:
    """Load the treasure types, gem values, magic item type, stocking, and unguarded tables.

    Returns:
        The frozen treasure tables.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("treasure.json")
    try:
        return TreasureTables.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"treasure.json failed validation: {error}") from error


@cache
def load_languages() -> LanguageCatalog:
    """Load the language list: Common plus the twenty Other Languages.

    Returns:
        The frozen language catalog.

    Raises:
        ContentValidationError: If the generated data is missing or fails validation.
    """
    data = _read("languages.json")
    try:
        return LanguageCatalog.model_validate(data)
    except ValidationError as error:
        raise ContentValidationError(f"languages.json failed validation: {error}") from error
